### ISSUE TITLE
TypeError: Expected float for argument 'alpha' not <tf.Variable 'network/Variable:0' shape=() dtype=float32_ref>.

### ISSUE THREAD

**Issue by jren2019** [sbrodehl/tf-boilerplate#5]
def prelu(net):
    alpha = 0.0  # tf.Variable(0.0, dtype=net.dtype)
    return tf.nn.leaky_relu(net, alpha)

Hello, this alpha should be a float number.

When I run your rcnn model, it complain this error
TypeError: Expected float for argument 'alpha' not <tf.Variable 'network/Variable:0' shape=() dtype=float32_ref>.

**Comment by sbrodehl** [comment]
Hi @jren2019 , thanks for the reply!

PReLU (Parametric Rectified Linear Unit) computes `f(x) = alpha * x for x < 0, f(x) = x for x >= 0`, where where alpha is a learned parameter.
Therefore it needs to be a variable.

I fixed this in #6.

Happy coding!
